[package]
name = "ast-description-lang"
authors = ["person93 <person93.person93@gmail.com>"]
version = "0.1.0-dev"
edition = "2021"
description = "A language to describe your language's AST"
license = "MIT OR Apache-2.0"

[dependencies]
