[package]
name = "example-foo"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.55"
chumsky = "0.8.0"
logos = "0.12.0"

[build-dependencies]
ast-description-lang = { path = "../.." }
toml = "0.5.8"
